create table async_task (
    id bigint primary key auto_increment,
    task_key varchar(191) not null,
    task_domain varchar(40) not null,
    task_type varchar(80) not null,
    payload_json json not null,
    result_json json null,
    created_by bigint null,
    space_id bigint null,
    resource_key varchar(191) not null,
    resource_version bigint not null default 1,
    status varchar(30) not null default 'PENDING_PUBLISH',
    attempt_version int not null default 0,
    next_trigger_type varchar(30) not null default 'INITIAL',
    max_attempts int not null default 4,
    next_retry_at timestamp null,
    lease_token varchar(64) null,
    lease_owner varchar(120) null,
    lease_until timestamp null,
    last_heartbeat_at timestamp null,
    cancel_requested_at timestamp null,
    cancel_requested_by bigint null,
    cancel_reason varchar(500) null,
    last_error_type varchar(40) null,
    last_error_code varchar(80) null,
    last_error_message varchar(1000) null,
    started_at timestamp null,
    finished_at timestamp null,
    row_version bigint not null default 0,
    created_at timestamp not null,
    updated_at timestamp not null,
    expire_at timestamp null,
    unique key uk_async_task_key (task_key),
    index idx_async_task_status_retry (status, next_retry_at),
    index idx_async_task_status_lease (status, lease_until),
    index idx_async_task_creator_time (created_by, created_at),
    index idx_async_task_space_time (space_id, created_at),
    index idx_async_task_resource_version (resource_key, resource_version),
    constraint fk_async_task_creator foreign key (created_by) references users(user_id),
    constraint fk_async_task_space foreign key (space_id) references spaces(id),
    constraint chk_async_task_status check (status in ('PENDING_PUBLISH','PENDING','RUNNING','RETRY_WAIT','SUCCESS','FAILED','CANCELED','SKIPPED_STALE'))
);

create table async_task_attempt (
    id bigint primary key auto_increment,
    task_id bigint not null,
    attempt_version int not null,
    trigger_type varchar(30) not null,
    worker_id varchar(120) not null,
    lease_token varchar(64) not null,
    status varchar(30) not null,
    started_at timestamp not null,
    last_heartbeat_at timestamp null,
    finished_at timestamp null,
    failure_type varchar(40) null,
    failure_code varchar(80) null,
    failure_message varchar(1000) null,
    retryable tinyint null,
    next_retry_at timestamp null,
    operator_id bigint null,
    operator_remark varchar(500) null,
    duration_ms bigint null,
    unique key uk_async_attempt_version (task_id, attempt_version),
    index idx_async_attempt_task_time (task_id, started_at),
    constraint fk_async_attempt_task foreign key (task_id) references async_task(id),
    constraint fk_async_attempt_operator foreign key (operator_id) references users(user_id),
    constraint chk_async_attempt_status check (status in ('RUNNING','SUCCESS','FAILED','RETRY_WAIT','CANCELED','SKIPPED_STALE'))
);

create table mq_outbox (
    id bigint primary key auto_increment,
    message_id varchar(64) not null,
    task_id bigint not null,
    expected_attempt_version int not null,
    exchange_name varchar(120) not null,
    routing_key varchar(120) not null,
    payload_json json not null,
    headers_json json null,
    status varchar(20) not null default 'PENDING',
    publish_attempts int not null default 0,
    next_publish_at timestamp not null,
    lease_token varchar(64) null,
    lease_owner varchar(120) null,
    lease_until timestamp null,
    confirmed_at timestamp null,
    last_error varchar(1000) null,
    created_at timestamp not null,
    updated_at timestamp not null,
    unique key uk_mq_outbox_message (message_id),
    index idx_mq_outbox_publish (status, next_publish_at),
    index idx_mq_outbox_lease (status, lease_until),
    constraint fk_mq_outbox_task foreign key (task_id) references async_task(id),
    constraint chk_mq_outbox_status check (status in ('PENDING','PUBLISHING','SENT'))
);

create table mq_inbox (
    id bigint primary key auto_increment,
    message_id varchar(64) not null,
    task_id bigint not null,
    expected_attempt_version int not null,
    consumer_name varchar(120) not null,
    status varchar(20) not null default 'RECEIVED',
    received_at timestamp not null,
    processed_at timestamp null,
    result_summary varchar(500) null,
    unique key uk_mq_inbox_message (message_id),
    index idx_mq_inbox_task (task_id, received_at),
    constraint fk_mq_inbox_task foreign key (task_id) references async_task(id),
    constraint chk_mq_inbox_status check (status in ('RECEIVED','PROCESSED','IGNORED','DEAD'))
);

alter table space_rag_task add column async_task_id bigint null, add index idx_space_rag_task_async (async_task_id);
alter table space_knowledge_pipeline_task add column async_task_id bigint null, add index idx_space_knowledge_task_async (async_task_id);
