alter table space_knowledge_document_profile
    add column raw_llm_output longtext null,
    add column normalized_profile_json longtext null,
    add column quality_detail_json longtext null,
    add column quality_issue_json longtext null,
    add column score_before_repair decimal(5,2) default 0.00,
    add column score_after_repair decimal(5,2) default 0.00,
    add column review_status varchar(30) not null default 'NOT_REQUIRED',
    add column review_reason varchar(1000) null,
    add column source_chunk_ids longtext null,
    add column source_chunk_count int not null default 0,
    add column source_character_count int not null default 0,
    add column schema_valid tinyint(1) not null default 0,
    add column repair_attempt int not null default 0,
    add column repair_reason varchar(1000) null,
    add column profile_version int not null default 1;

create table if not exists space_knowledge_pipeline_event (
    id bigint primary key auto_increment,
    task_id bigint not null,
    space_id bigint not null,
    document_id bigint,
    stage varchar(60) not null,
    event_type varchar(40) not null,
    event_status varchar(30) not null,
    message varchar(1000),
    input_summary varchar(1000),
    output_summary varchar(1000),
    error_code varchar(80),
    error_message varchar(1000),
    event_time timestamp not null,
    duration_ms bigint,
    trace_id varchar(80),
    attempt_no int not null default 1,
    created_at timestamp not null,
    index idx_space_knowledge_event_task_id (task_id),
    index idx_space_knowledge_event_space_id (space_id),
    index idx_space_knowledge_event_document_id (document_id),
    index idx_space_knowledge_event_stage (stage),
    index idx_space_knowledge_event_trace_id (trace_id)
);
